### ISSUE TITLE
Half-Dragon Missing Immunities

### ISSUE THREAD

**Issue by Morkai-bde** [Heliomance/HeroForge-Anew#100]
Half-dragons elemental immunities do not show up on the sheet

To fix replace:
="sleep, paralysis" & IF($BC36,", " & CLEAN(INDEX(TblCreatureInfo,$AW36,COLUMN())),"")
With:
="sleep, paralysis" & IF($BC36,", " & CLEAN(INDEX(TblCreatureInfo,$AW36,COLUMN(W1))),"")

In cell V36 under template info

**Comment by Heliomance** [comment]
Check the latest development version. That section of the sheet has been completely restructured, it should be working.

**Comment by Morkai-bde** [comment]
Still not working in the sheet I just downloaded, , sleep and paralysis show up but not the element

**Comment by Heliomance** [comment]
Did you get it from the main branch or the development branch?

**Comment by Morkai-bde** [comment]
Dev branch as you said, Below is a comparison my old sheet with the changed formula is on the left and the one I downloaded is on the right
![error](https://cloud.githubusercontent.com/assets/20994840/18205307/9e0f46aa-7121-11e6-9df3-736935c7abe2.png)

**Comment by Morkai-bde** [comment]
nvm, I see my mistake, I use the xls version instead of the xlsm because the latter does not open on my pc at all

**Comment by Heliomance** [comment]
You actually need to run the Launcher file for it to work properly. But if xlsms don't open on your computer, you're not going to be able to use any future versions of HeroForge.
